const sites = [
    {
        "name": "Google",
        "icon": "carbon:youtube",
        "url": "https://www.Google.com/",
        "color": "#ff0000",
        "description": "全球最大社交平台",
        "categories": ["搜索引擎"],
        "keywords": "谷歌 google 搜索",
    },
    {
        "name": "facebook",
        "icon": "carbon:youtube",
        "url": "https://www.facebook.com/",
        "color": "#ff0000",
        "description": "全球最大社交平台",
        "categories": ["社交媒体"],
        "keywords": "非死不可 facebook 社交 脸书",
    },
    {
        "name": "X (Twitter)",
        "icon": "carbon:youtube",
        "url": "https://x.com/",
        "color": "#ff0000",
        "description": "全球最大社交平台",
        "categories": ["社交媒体"],
        "keywords": "推特 twitter 社交 叉 x",
    },
    {
        "name": "YouTube",
        "icon": "carbon:youtube",
        "url": "https://www.youtube.com/",
        "color": "#ff0000",
        "description": "全球最大视频网站",
        "categories": ["影音流媒体"],
        "keywords": "油管 youtube 视频 流媒体",
    },
    {
        "name": "Spotify",
        "icon": "carbon:spotify",
        "url": "https://www.spotify.com/",
        "color": "",
        "description": "全球最大视频网站",
        "categories": ["影音流媒体"],
        "keywords": "声破天 spotify 音乐 流媒体",
    },
    {
        "name": "NETFLIX",
        "icon": "carbon:spotify",
        "url": "https://www.netflix.com/",
        "color": "",
        "description": "全球最大视频网站",
        "categories": ["影音流媒体"],
        "keywords": "奈飞 netflix 视频 流媒体",
    },
    {
        "name": "TikTok",
        "icon": "carbon:spotify",
        "url": "https://www.tiktok.com/",
        "color": "",
        "description": "全球最大视频网站",
        "categories": ["影音流媒体"],
        "keywords": "抖音 tiktok 短视频 流媒体",
    },
    {
        "name": "動畫瘋",
        "icon": "carbon:spotify",
        "url": "https://ani.gamer.com.tw/",
        "color": "",
        "description": "全球最大视频网站",
        "categories": ["影音流媒体"],
        "keywords": "巴哈姆特 动画疯 流媒体",
    },
    {
        "name": "hulu",
        "icon": "carbon:spotify",
        "url": "https://www.hulu.com/",
        "color": "",
        "description": "全球最大视频网站",
        "categories": ["影音流媒体"],
        "keywords": "抖音 tiktok 短视频 流媒体",
    },
]
